<<<<<<< HEAD
import { Award, Check, Star, Trophy } from "lucide-react";
import PageIntro from "@/components/PageIntro";
import { useApp } from "@/lib/AppContext";

const rows = [{ key: "huruf", emoji: "🔤", label: "Huruf" }, { key: "angka", emoji: "🔢", label: "Angka" }, { key: "hewan", emoji: "🐶", label: "Hewan" }, { key: "buah", emoji: "🍎", label: "Buah" }, { key: "kendaraan", emoji: "🚗", label: "Kendaraan" }, { key: "permainan", emoji: "🎮", label: "Permainan" }];

export default function Rewards() {
  const { stars, progress } = useApp();
  return <div data-testid="page-rewards"><PageIntro emoji="⭐" title="Bintangku" description="Lihat semua kemajuan belajar yang sudah kamu buat!" color="yellow" />
    <section data-testid="rewards-hero" className="relative overflow-hidden rounded-[32px] border-4 border-white bg-gradient-to-br from-amber-300 via-yellow-200 to-orange-100 p-6 shadow-xl sm:p-8"><div className="absolute -right-2 -top-6 text-8xl opacity-30">⭐</div><div className="relative flex flex-col items-center gap-4 text-center sm:flex-row sm:text-left"><div data-testid="rewards-star-count" className="grid size-28 shrink-0 place-items-center rounded-full border-8 border-white/80 bg-yellow-400 font-heading text-5xl font-black text-amber-900 shadow-[0_8px_0_#D97706]">{stars}</div><div><p data-testid="rewards-kicker" className="font-heading text-sm font-black uppercase tracking-widest text-amber-800">Koleksi bintang</p><h2 data-testid="rewards-title" className="font-heading text-3xl font-black text-amber-950">Hebat sekali! 🎉</h2><p data-testid="rewards-copy" className="mt-1 font-bold text-amber-900/80">Terus bermain dan belajar. Tidak ada lomba, yang penting kamu senang!</p></div></div></section>
    <section data-testid="rewards-progress-section" className="mt-5 rounded-[32px] border-4 border-white bg-white/85 p-5 shadow-xl sm:p-7"><div className="flex items-center justify-between"><h2 data-testid="rewards-progress-title" className="font-heading text-2xl font-black text-slate-800">Progress belajar</h2><Trophy data-testid="rewards-trophy-icon" className="size-8 text-amber-500" /></div><div className="mt-5 space-y-4">{rows.map((row) => <div key={row.key} data-testid={`rewards-progress-${row.key}`}><div className="mb-1 flex items-center justify-between"><span data-testid={`rewards-progress-${row.key}-label`} className="font-black text-slate-700">{row.emoji} {row.label}</span><span data-testid={`rewards-progress-${row.key}-value`} className="font-heading font-black text-slate-500">{progress[row.key as keyof typeof progress]}%</span></div><div className="h-4 overflow-hidden rounded-full bg-slate-100"><div data-testid={`rewards-progress-${row.key}-bar`} className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-sky-500 transition-all duration-500" style={{ width: `${progress[row.key as keyof typeof progress]}%` }} /></div></div>)}</div></section>
    <section data-testid="rewards-badges" className="mt-5 grid gap-3 sm:grid-cols-3"><div data-testid="rewards-badge-first" className={`rounded-3xl border-4 border-white p-5 shadow-md ${stars >= 1 ? "bg-emerald-100" : "bg-slate-100 opacity-70"}`}><Award className="size-8 text-emerald-500" /><h3 data-testid="rewards-badge-first-title" className="mt-3 font-heading text-lg font-black">Bintang pertama</h3><p data-testid="rewards-badge-first-copy" className="mt-1 text-sm font-bold text-slate-500">{stars >= 1 ? "Terbuka! Kamu hebat." : "Ayo kumpulkan bintang."}</p></div><div data-testid="rewards-badge-progress" className="rounded-3xl border-4 border-white bg-sky-100 p-5 shadow-md"><Check className="size-8 text-sky-500" /><h3 data-testid="rewards-badge-progress-title" className="mt-3 font-heading text-lg font-black">Rajin belajar</h3><p data-testid="rewards-badge-progress-copy" className="mt-1 text-sm font-bold text-slate-500">Progress kecil tetap berarti.</p></div><div data-testid="rewards-badge-star" className="rounded-3xl border-4 border-white bg-pink-100 p-5 shadow-md"><Star className="size-8 fill-pink-400 text-pink-500" /><h3 data-testid="rewards-badge-star-title" className="mt-3 font-heading text-lg font-black">Senyum ceria</h3><p data-testid="rewards-badge-star-copy" className="mt-1 text-sm font-bold text-slate-500">Belajar sambil tersenyum!</p></div></section>
  </div>;
=======
import { Award, Check, Star, Trophy } from "lucide-react";
import PageIntro from "@/components/PageIntro";
import { useApp } from "@/lib/AppContext";

const rows = [{ key: "huruf", emoji: "🔤", label: "Huruf" }, { key: "angka", emoji: "🔢", label: "Angka" }, { key: "hewan", emoji: "🐶", label: "Hewan" }, { key: "buah", emoji: "🍎", label: "Buah" }, { key: "kendaraan", emoji: "🚗", label: "Kendaraan" }, { key: "permainan", emoji: "🎮", label: "Permainan" }];

export default function Rewards() {
  const { stars, progress } = useApp();
  return <div data-testid="page-rewards"><PageIntro emoji="⭐" title="Bintangku" description="Lihat semua kemajuan belajar yang sudah kamu buat!" color="yellow" />
    <section data-testid="rewards-hero" className="relative overflow-hidden rounded-[32px] border-4 border-white bg-gradient-to-br from-amber-300 via-yellow-200 to-orange-100 p-6 shadow-xl sm:p-8"><div className="absolute -right-2 -top-6 text-8xl opacity-30">⭐</div><div className="relative flex flex-col items-center gap-4 text-center sm:flex-row sm:text-left"><div data-testid="rewards-star-count" className="grid size-28 shrink-0 place-items-center rounded-full border-8 border-white/80 bg-yellow-400 font-heading text-5xl font-black text-amber-900 shadow-[0_8px_0_#D97706]">{stars}</div><div><p data-testid="rewards-kicker" className="font-heading text-sm font-black uppercase tracking-widest text-amber-800">Koleksi bintang</p><h2 data-testid="rewards-title" className="font-heading text-3xl font-black text-amber-950">Hebat sekali! 🎉</h2><p data-testid="rewards-copy" className="mt-1 font-bold text-amber-900/80">Terus bermain dan belajar. Tidak ada lomba, yang penting kamu senang!</p></div></div></section>
    <section data-testid="rewards-progress-section" className="mt-5 rounded-[32px] border-4 border-white bg-white/85 p-5 shadow-xl sm:p-7"><div className="flex items-center justify-between"><h2 data-testid="rewards-progress-title" className="font-heading text-2xl font-black text-slate-800">Progress belajar</h2><Trophy data-testid="rewards-trophy-icon" className="size-8 text-amber-500" /></div><div className="mt-5 space-y-4">{rows.map((row) => <div key={row.key} data-testid={`rewards-progress-${row.key}`}><div className="mb-1 flex items-center justify-between"><span data-testid={`rewards-progress-${row.key}-label`} className="font-black text-slate-700">{row.emoji} {row.label}</span><span data-testid={`rewards-progress-${row.key}-value`} className="font-heading font-black text-slate-500">{progress[row.key as keyof typeof progress]}%</span></div><div className="h-4 overflow-hidden rounded-full bg-slate-100"><div data-testid={`rewards-progress-${row.key}-bar`} className="h-full rounded-full bg-gradient-to-r from-cyan-400 to-sky-500 transition-all duration-500" style={{ width: `${progress[row.key as keyof typeof progress]}%` }} /></div></div>)}</div></section>
    <section data-testid="rewards-badges" className="mt-5 grid gap-3 sm:grid-cols-3"><div data-testid="rewards-badge-first" className={`rounded-3xl border-4 border-white p-5 shadow-md ${stars >= 1 ? "bg-emerald-100" : "bg-slate-100 opacity-70"}`}><Award className="size-8 text-emerald-500" /><h3 data-testid="rewards-badge-first-title" className="mt-3 font-heading text-lg font-black">Bintang pertama</h3><p data-testid="rewards-badge-first-copy" className="mt-1 text-sm font-bold text-slate-500">{stars >= 1 ? "Terbuka! Kamu hebat." : "Ayo kumpulkan bintang."}</p></div><div data-testid="rewards-badge-progress" className="rounded-3xl border-4 border-white bg-sky-100 p-5 shadow-md"><Check className="size-8 text-sky-500" /><h3 data-testid="rewards-badge-progress-title" className="mt-3 font-heading text-lg font-black">Rajin belajar</h3><p data-testid="rewards-badge-progress-copy" className="mt-1 text-sm font-bold text-slate-500">Progress kecil tetap berarti.</p></div><div data-testid="rewards-badge-star" className="rounded-3xl border-4 border-white bg-pink-100 p-5 shadow-md"><Star className="size-8 fill-pink-400 text-pink-500" /><h3 data-testid="rewards-badge-star-title" className="mt-3 font-heading text-lg font-black">Senyum ceria</h3><p data-testid="rewards-badge-star-copy" className="mt-1 text-sm font-bold text-slate-500">Belajar sambil tersenyum!</p></div></section>
  </div>;
>>>>>>> 75f147cdab0e73e8ad3ef48bc31de1eea693a8f8
}